name: 'Discord Notify With Commits'
description: 'Send a notification to Discord channel'
author: 'Bijaya Oli'
inputs:
  webhook-url:
    description: 'Discord webhook URL'
    required: true
  message:
    description: 'Notification message'
    required: true
runs:
  using: 'node12'
  main: 'index.js'
dependencies:
  - '@actions/core@1.5.0'
